version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    container_name: xilriws
    command: --api.insecure=true --providers.docker
    ports:
      - "5090:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  xilriws:
    image: xilriws
    restart: unless-stopped
    volumes:
      - ./xilriws.json:/xilriws/config.json
    expose:
    - "5090"
    labels:
      - traefik.http.routers.xilriws.rule=HostRegexp(`{catchall:.*}`)
    deploy:
      replicas: 1